Execute simple check before enable BungeeCord hook.
AuthMe/AuthMeReloaded pull request #2572
Opened 2022-07-04 13:09 UTC by Ghost-chu

This PR added a simple check that check spigot.yml -> settings.bungeecord status by using AuthMe built-in method bukkitService.isBungeeCordConfiguredForSpigot() and disable hook if it enabled and not behind an BungeeCord proxy.

Register plugin message channel without BungeeCord proxy will allow attacker send fake login payload to treat AuthMe login with Plugin Message for him and bypass the user login.

Fixed:
https://github.com/AuthMe/AuthMeReloaded/issues/2571
https://github.com/AuthMe/AuthMeReloaded/issues/2566
https://github.com/AuthMe/AuthMeReloaded/issues/2559

2022-07-04 14:56 UTC, games647 requested changes
Good idea, but maybe we should also an entry to the `SettingsWarner`, so that we don't disable functionality for the user without telling them the reason. There might be cases where people actually forget to turn on this BungeeCord setting (the spigot.yml one).

2022-07-04 15:11 UTC, Ghost-chu commented on src/main/java/fr/xephi/authme/service/bungeecord/BungeeReceiver.java
> +            this.isEnabled = bukkitService.isBungeeCordConfiguredForSpigot().orElse(false);
The check rule has been append to SettingsWarner and waiting for review.

Note: My native language not English so I can't promise the spelling and grammer are correct, may require additional review for them.

2022-07-06 07:10 UTC, games647 approved these changes
!LGTM

!["!LGTM" (Looks good to me) in pixel GitHub commit history where pixel represents a day of the year with a high commit count](https://user-images.githubusercontent.com/1957196/147462701-695cd280-3a25-48d6-979e-10e0c75d8d3c.png)

Although this potentially break Velocity support. However we don't support Velocity officially, so I think it's fine.

2022-07-06 07:40 UTC, Ghost-chu commented
@games647 It's now squashed to one single commit now ;)

2022-07-06 13:08 UTC, merged